version: '3'

services:
  browserquest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - HOST_ADDRESS=browserquest-php-docker-llm.onrender.com
      - HOST_PORT=443
      - PORT=8787
